user_file = open("USER.txt",'w')
print("아이디를 정하세요 : ")
user_id = input()
user_file.write(user_id)
print()
user_file.write("\n")
print("비밀번호를 정하세요 : ")
user_pw = input()
user_file.write(user_pw)
user_file.close()